# Generated by Django 4.0.2 on 2022-02-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='high_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
