# Generated by Django 4.0 on 2022-02-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gallery',
            new_name='Photo',
        ),
    ]
